Enable the upload button after opening a config
MobiFlight/MobiFlight-Connector pull request #1001
Opened 2022-11-05 22:40 UTC by neilenns

Enable the upload button whenever a config is loaded successfully.

2022-11-15 16:50 UTC, DocMoebiuz commented on UI/Panels/Settings/MobiFlightPanel.cs
> +                uploadToolStripButton.Enabled = true;
there is nothing in the code that disables the button on opening inside this function. That's why I find the proposed solution doesn't fix the problem.

In your screen recoding the device is not selected by the user, but when you click the open button- i would guess that "afterselect"-event is not properly triggered in this case.

So the real fix should be to properly "select" the node and trigger the `mfModulesTreeView_AfterSelect` correctly.

Expected behavior:
* If no board is selected, the toolbar should be deactivated.
* If one board is selected, the toolbar items become active.
* If I open a new config, the board should stay selected as active, and all buttons in the toolbar therefore active too.

2022-11-15 16:50 UTC, DocMoebiuz requested changes
see comment

2022-11-15 16:52 UTC, DocMoebiuz commented
Possibly related to #925

2022-11-16 20:21 UTC, neilenns commented
@DocMoebiuz I agree the fix in this PR isn't great. I couldn't find a good way to fire the actual existing method for when selection changes. I tried forcing the selection to the active board but that didn't work. Am open to other ideas, or if you want to try coding up a fix.

2022-11-16 22:09 UTC, DocMoebiuz commented
I don't want to spend too much effort on this but I wonder why the UI doesn't behave correctly in the first place. At what circumstance is it greying out the button? I looked through the AfterSelect method - as soon as the board is a MF board and gets selected then the toolbar should become enabled.

We have the other issue #925 where this could be the same root cause that triggers this behavior.

To reproduce this, what is needed?

A fresh MF board with no devices?
what else?

2022-11-16 22:12 UTC, neilenns commented
@DocMoebiuz My suspicion is one of these two situations are what makes it happen:

* Only one board connected
* The board connected has no devices on it yet

Haven't tested it deeply to find out which case causes it though.

When I was debugging I did confirm that AfterSelect is triggered when I first open the dialog, but it never gets called again after I click on the Open button. Forcing it to get called after the Open dialog closes is a good solution but I couldn't get that to work.

2022-12-03 23:53 UTC, closed without merging