7 segment support decimal
MobiFlight/MobiFlight-Connector pull request #1010
Opened 2022-11-15 21:14 UTC by DocMoebiuz

fixes #1009 

Confirmations:
* decimal value can be sent to the 7-segment display
* decimal point is displayed in the correct position next to the the number without using an additional 7-segment digit
* masking is correctly applied, e.g. if we display the number only on the last three digits of an 8 digit module the decimal point is placed correctly

2022-11-16 20:23 UTC, neilenns commented on MobiFlight/MobiFlightLedModule.cs
> +            value = String.Join("", strValueParts);
Instead of calling this `value` and then having to re-join the string later if there is a decimal, why not call this `valueWithoutDecimals`?

2022-11-16 20:23 UTC, neilenns commented on MobiFlight/MobiFlightLedModule.cs
> +                points = CalculateCorrectPoints(String.Join(".", strValueParts), mask);
Then here instead of having to re-join you can just pass in the original `value`.

2022-11-16 20:25 UTC, neilenns commented on MobiFlight/MobiFlightLedModule.cs
> +            for (byte digit=0; digit<8; digit++)
Should this be `var` instead of `byte`?

2022-11-16 20:26 UTC, neilenns commented on MobiFlight/MobiFlightLedModule.cs
> +                    // then we stay on the digit one more time
I don't understand this code comment. Why does it say "stay on the digit" but decrement `digit`?

2022-11-16 20:27 UTC, neilenns requested changes
This also works with reversed display?

2022-11-16 23:18 UTC, neilenns commented on MobiFlight/MobiFlightLedModule.cs
> +            value = String.Join("", strValueParts);
Thinking about this even more, why even do this at all? Just pass `value` to `CalcuateCorrectPoints()` and when you need the string without decimals do `value.Replace('.', '')`;

2022-11-27 16:22 UTC, DocMoebiuz commented
> This also works with reversed display?

good point. I don't know exactly but I hope that we will get the feedback during the beta phase.

2022-11-30 01:16 UTC, merged