Multiple baud rate flashing
MobiFlight/MobiFlight-Connector pull request #1016
Opened 2022-11-22 18:59 UTC by neilenns

This adds support for trying different baud rates when flashing a given board. It is primarily intended to resolve the "which baud rate should we use for a Nano" problem, but is done in a general fashion that could apply to any device that uses avrdude to flash.

Changes include:

1. Version 7.0 of avrdude to get the `-x attempts` command line parameter. (I pulled the x86 version of avrdude)
2. New `TimeoutForFirmwareUpdate` property in the `.board.json` file to remove a hard-coded timeout value I missed in the original .board.json implementation
3. New `Attempts` property in the `.board.json` file to control how many times avrdude should attempt connections to a board
4. Change `BaudRate` property to `BaudRates` (an array) in the `.board.json` files
5. Schema updates to reflect the property additions/changes 
6. New `Migrate()` method on the `Board` object to ensure any random old `.board.json` files that might exist will still work
7. Update `RunAvrDude()` to use the `Attempts` property and to loop over the `BaudRates` until one works. This really is the meat of the change to make this all work and is pretty small.

2022-11-22 19:03 UTC, neilenns commented on Boards/arduino_mega.board.json
> +    "Attempts":  3,
avrdude defaults to 10 attempts. If we want to keep exact behaviour with the prior release of MobiFlight we could make this 10 for all non-Nano boards. Seems excessive though, either the connection works or it fails. Setting this to 3 (or 2 or even 1) would make the non-Nano boards fail faster during the flashing process.

2022-11-22 19:03 UTC, neilenns commented on Boards/mfboard.schema.json
> +  "$schema": "https://json-schema.org/draft/2019-09/schema#",
Newer release of the JSON Schema to get access to the `deprecated` property.

2022-11-22 19:03 UTC, neilenns commented on Boards/mfboard.schema.json
> -        "MaxInputShifters",
This was a duplicate entry in the schema I cleaned up.

2022-11-22 19:05 UTC, neilenns commented on MobiFlight/Board.cs
> +        public int TimeoutForFirmwareUpdate = 15000;
`15000` is the original hardcoded value so it's used as the default here. If it is omitted from the `.board.json` file the default gets used.

2022-11-22 19:06 UTC, neilenns commented on MobiFlight/MobiFlightFirmwareUpdater.cs
> -            String C = board.AvrDudeSettings.Programmer;
These three lines should have been removed back when I did the .board.json work. They aren't needed and the properies are now just referenced directly in the `anyCommand` string construction.

2022-11-22 19:06 UTC, neilenns commented on MobiFlight/MobiFlightFirmwareUpdater.cs
> +            foreach (var baudRate in board.AvrDudeSettings.BaudRates)
The meat of the change. One additional `foreach` loop to try all the baud rates. So simple!

2022-11-22 19:07 UTC, neilenns commented on MobiFlight/MobiFlightFirmwareUpdater.cs
> +                Log.Instance.log($"{proc1.FileName} {anyCommand}", LogSeverity.Debug);
This used to be two log lines. Combined to one for ease of viewing in the logs.

2022-11-30 02:49 UTC, DocMoebiuz approved these changes
Really cool change. Thanks!

2022-11-30 02:52 UTC, DocMoebiuz requested changes
I think it would make sense to include the nano board json for which this is all done and then we could also call #579 done.

I also would propose to set all other boards' retry value to 1 because we don't expect that a retry is required. So if it fails, it can fail fast

2022-11-30 04:15 UTC, neilenns commented
Json added, updated retries on the other boards.

2022-11-30 04:17 UTC, neilenns commented
Once this merges we'll still need to update the firmware builds to build the nano firmware, update the vs project to include it in desktop builds, and I think that's it?

2022-12-04 10:00 UTC, DocMoebiuz commented
> Once this merges we'll still need to update the firmware builds to build the nano firmware, update the vs project to include it in desktop builds, and I think that's it?

Yeah, why not do that and then we can include the .hex file right away with this PR? and then this is really the complete nano support.

2022-12-08 00:20 UTC, DocMoebiuz commented
i really would like to merge it but without the nano hex file it feels incomplete.

2022-12-08 00:58 UTC, neilenns commented
Nano firmware PR: https://github.com/MobiFlight/MobiFlight-FirmwareSource/pull/223

2022-12-08 17:05 UTC, DocMoebiuz approved these changes
Mercy boocoo!

2022-12-08 17:21 UTC, merged