When clicking on the reset board you are now asked if you are sure
MobiFlight/MobiFlight-Connector pull request #1085
Opened 2023-01-20 19:46 UTC by Pitj3

When clicking on the reset board you are now asked if you are sure you want to reset the config as per request #1084.

2023-01-20 23:53 UTC, DocMoebiuz requested changes
Thanks!

The message should read differently, it is not about config, you are resetting your board back to standard arduino and you will lose all information stored on it.

`Do you really want to uninstall the MobiFlight firmware? 
All your data will be removed from the board.`

I also believe that I switched to "Du" in the new German dialog messages.

`Möchtest Du wirklich die MobiFlight Firmware deinstallieren?
Alle Deine Daten werden vom Board gelöscht.`

2023-01-21 13:34 UTC, Pitj3 commented
Changes have been made as requested

2023-01-21 14:14 UTC, DocMoebiuz commented
Thanks!
Please always mention the issue(s) that this PR "fixes" or "relates to" or "is part of"

With "fixes #..." the according issue will be set to "closed" automatically once the PR is merged.

Please also mention a short outline of the introduced changes, or touched ares, e.g.:

- [ ] Added a new message box
- [ ] i18n - added EN and DE messages

2023-01-21 14:16 UTC, DocMoebiuz requested changes
see my last comment and the typo here.

2023-01-21 14:16 UTC, DocMoebiuz commented on ProjectMessages/ProjectMessages.resx
> +    <value>Do you really want to uninstall the MobiFlight firmware?  All your data will be removed from the board.</value>
Tiny little typo. two spaces.

2023-01-21 16:27 UTC, DocMoebiuz approved these changes

2023-01-21 16:27 UTC, merged