Dynamic board detection
MobiFlight/MobiFlight-Connector pull request #1364
Opened 2023-10-28 17:31 UTC by DocMoebiuz

This PR rewrites the entire board detection and enumeration logic and makes it totally dynamic.

Confirmations:
- [ ] All connected boards are detected on start up
- [ ] Boards connected after MobiFlight start will be detected and are available for config thereafter
  - [ ] board shows in the mobiflight boards settings dialog
  - [ ] device config upload possible
  - [ ] output / input configs show them in the list
  - [ ] Old firmware dialog will show including the option to flash it
- [ ] Boards disconnected after Mobiflight will be removed from any list
  - [ ] mobiflight boards settings dialog
  - [ ] output / input configs 
- [ ] Boards can be flashed

fixes #1091 
related to #1216 
related to #1149

2023-10-28 17:52 UTC, neilenns requested changes
Love the approach overall, super cool change!

2023-10-28 17:52 UTC, neilenns commented on MobiFlight/Monitors/UsbDeviceMonitor.cs
> +                // Issue 1074: Failing to check for IsReady caused an IOException on certain machines
The refactor of this into a new class is cool but it lost an important bug fix from the old code:

```C#
// Issue 1089: Network drives take *forever* to return the drive info slowing down startup. Only check removable drives.
                if (drive.DriveType != DriveType.Removable)
                {
                    Log.Instance.log($"Drive {drive.Name} ({drive.DriveType}) isn't a removable drive, skipping.", LogSeverity.Debug);
                    continue;
                }
```

2023-10-29 01:36 UTC, JaimeLeon2 commented
Sebastian,
Tested this build.  Installed in a new folder.  

It started looking very well.  I was able at first to connect and disconnect boards and I was amazed that MF Connector could correctly and automatically detect the boards going in and out of line.  Then I started MSFS, loaded the FBW A320 mcc and linked the config.  I started to test with the sim running.

When I tried to disconnect and reconnect a board after auto-loading the FBW A320 config.  Mobiflight crashed.  Something broke in my installation as the automatic detection of boards seem to disappear.  Something must have deactivate it.  I restarted Mobiflight several times and it detected all the boards connected at start, but failed to detect when I connected another board while running.  Also failed to detect when I disconnected a board while running.

I tried to reinstall the PR by copying the files over the existing files.  Same result.
I tried deleting the folder contents and recopying everything.  Same result.
I tried deleting the config file in Appdata\Local\Mobiflight.  After reinstalling the PR now I get the normal start after an update, but while loading the default mcc file, it crashes consistently.  No error message from Mobiflight.  It just quits.

I looked in Event Viewer and this is the message I get.  I tried deleting all the config files, but it keeps crashing.

Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2+ValueCollection+Enumerator[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at MobiFlight.MobiFlightCache.Stop()
   at MobiFlight.ExecutionManager.Stop()
   at MobiFlight.ExecutionManager.ModuleCache_ModuleConnected(System.Object, System.EventArgs)
   at MobiFlight.MobiFlightCache+<SerialPortMonitor_PortAvailable>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

2023-11-03 11:37 UTC, DocMoebiuz commented
<img width="428" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/61b6b95c-8c33-474b-aec5-d2a43ab7873b">

rename needed

2023-11-05 23:40 UTC, merged