Renamed kav's board.json file and customDevice types
MobiFlight/MobiFlight-Connector pull request #1400
Opened 2023-11-14 12:09 UTC by elral

Rename board.json file for KAV's displays and rename accordingly the device types in the device.json file

2023-11-16 05:44 UTC, elral commented
Fixed also a wrong MF type in generic I2C

2023-11-17 00:49 UTC, DocMoebiuz requested changes
only the FW file name has to be changed. the rest is looking great!

2023-11-17 00:49 UTC, DocMoebiuz commented on Boards/kav_mega.board.json.inactive
> +    "FirmwareBaseName": "kav_mega",
the firmware file has to be renamed too:
https://github.com/elral/MobiFlight-Connector/blob/renaming_KAV_customDevices/firmware/kav_efis_fcu_mega_2_4_4.hex

2023-11-17 11:32 UTC, DocMoebiuz approved these changes
Dankeschön

2023-11-17 11:33 UTC, merged