Code cleanup
MobiFlight/MobiFlight-Connector pull request #1407
Opened 2023-11-16 14:08 UTC by neilenns

Fixes #1406 

* Move method calls out of the timer Stopped() event handler
* Call Stop() instead of setting the timer's state via a property

2023-11-16 14:08 UTC, neilenns commented
Is this what you were thinking @DocMoebiuz ?

2023-11-16 21:08 UTC, DocMoebiuz commented on MobiFlight/ExecutionManager.cs
>                  isExecuting = false;
can be removed. is done in `Stop()`

2023-11-16 21:09 UTC, DocMoebiuz requested changes
Exactly. The one line can also be removed.

2023-11-16 21:37 UTC, neilenns commented on MobiFlight/ExecutionManager.cs
>                  isExecuting = false;
Fixed

2023-11-17 00:52 UTC, DocMoebiuz approved these changes
Cool!

2023-11-17 00:58 UTC, DocMoebiuz approved these changes

2023-11-17 00:58 UTC, merged