Fix for #643-Incorrect update of pin selection combo boxes
MobiFlight/MobiFlight-Connector pull request #645
Opened 2022-01-05 23:16 UTC by GioCC

TEST VERSION, LIMITED TO `LedSegment`!
Needs more thorough testing, but seems good.
@DocMoebiuz could you have a look as soon as convenient? If the solution is approved, I can track the other devices where the modification is required.

_PS I added some small comments here and there for orientation, is it OK as a general guideline?_

2022-01-10 18:02 UTC, DocMoebiuz commented
Another approach could have been to sync the setting back to the module and refresh the fields again. It looks like to me that the current approach is very invasive.

So to say it in other words. At the moment if I make a change, then switch to another device and come back, the drop-downs should be updated accordingly, right? So after leaving the current pin drop down, all we would have to do is sync the changes and re-init the panel and we should be able to re-use all existing logic.

2022-01-10 18:59 UTC, GioCC commented
Hm, you definitely have a point there. It seems more practical indeed.
At a first glance, though, I'm not really convinced though, because:
- (main reason) calling a re-sync would basically mean to make use syncPanelWithSelectedDevice(), which is outside of the panel class responsibility and scope;
- I don't really see this approach as "invasive": a little cumbersome, yes, but what it does different from the existing procedure is basically just the added required operations which are in the first part of the "update_all()" method (the rest is just refactoring), and everything is closely contained inside the class.
I have to admit that I tend to see the "let's rebuild everything again from scratch" approach in general as a little wasteful, but then again, I'm more used to embedded development, and in C#/.NET different rules may sensibly apply.

2022-01-10 19:39 UTC, GioCC commented
So, what about I throw a "resync" exception and have the parent catch it?

2022-02-06 12:15 UTC, DocMoebiuz requested changes
Thanks for all the effort. It seems to be working.

Improvements:
* It is really hard to review the changes because sometimes, some lines were only moved around, and indenting got changed - (e.g. MFAnalogPanel.cs). 
* There are also many commented lines of code. Please remove those since we have git for history. 
* Please don't put comments at the end of the line. Always better on top, before the code.
* Also for some reason it seems that the git history at least on my local main branch is not linear anymore. When you merge the main branch, do you merge rebase  or simply merge?
* Method normally are CamelCase.
* EventHandlers in C# have an "_eventname" when the Designer adds them, so that's why some methods contain an "_"

2022-02-06 12:23 UTC, DocMoebiuz requested changes
Thanks for all the effort. It seems to be working.

Improvements:
* It is really hard to review the changes because sometimes, some lines were only moved around, and indenting got changed - (e.g. MFAnalogPanel.cs). 
* There are also many commented lines of code. Please remove those since we have git for history. 
* Please don't put comments at the end of the line. Always better on top, before the code.
* Also for some reason it seems that the git history at least on my local main branch is not linear anymore. When you merge the main branch, do you merge rebase  or simply merge?
* Method normally are CamelCase.
* EventHandlers in C# have an "_eventname" when the Designer adds them, so that's why some methods contain an "_"

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFStepperPanel.cs
> +            ////ComboBoxHelper.BindMobiFlightFreePins(mfPin1ComboBox, Pins, stepper.Pin1);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFStepperPanel.cs
> +            ////if (mfPin1ComboBox.Items.Count > 4)
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFStepperPanel.cs
> +            ////stepper.Pin1 = mfPin1ComboBox.SelectedItem.ToString();
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +            ////shiftRegister.LatchPin = mfPin1ComboBox.SelectedItem.ToString();
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +            ////mfPin1ComboBox.SelectedValue = byte.Parse(shiftRegister.LatchPin);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +            ////if (mfPin1ComboBox.Items.Count > 2)
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +            ////ComboBoxHelper.BindMobiFlightFreePins(mfPin1ComboBox, Pins, shiftRegister.LatchPin);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFServoPanel.cs
> +            ////if (mfPinComboBox.Items.Count > 0) {
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFOutputPanel.cs
> +            ////if (mfPinComboBox.Items.Count > 0) {
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            //mfPin1ComboBox.SelectedValue = byte.Parse(ledModule.DinPin);  // moved inside BindMobiFlightFreePins()
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            //mfPin2ComboBox.SelectedValue = byte.Parse(ledModule.ClsPin);  // moved inside BindMobiFlightFreePins()
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            //mfPin3ComboBox.SelectedValue = byte.Parse(ledModule.ClkPin);  // moved inside BindMobiFlightFreePins()
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            //if (mfPin1ComboBox.Items.Count > 2) {
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            pinList = Pins; // Keep pin list stored
put the comment on top/before

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFInputShiftRegisterPanel.cs
> +            ////ComboBoxHelper.BindMobiFlightFreePins(mfPin1ComboBox, Pins, inputShiftRegister.LatchPin);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFInputShiftRegisterPanel.cs
> +            ////if (mfPin1ComboBox.Items.Count > 2) {
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFInputShiftRegisterPanel.cs
> +            ////ComboBoxHelper.SetSelectedItem(mfPin1ComboBox, inputShiftRegister.LatchPin);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFEncoderPanel.cs
> +            ////encoder.PinLeft = mfLeftPinComboBox.SelectedItem.ToString();
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFEncoderPanel.cs
> +            //mfLeftPinComboBox.SelectedValue = byte.Parse(encoder.PinLeft);  // moved inside BindMobiFlightFreePins()
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFEncoderPanel.cs
> +            //mfRightPinComboBox.SelectedValue = byte.Parse(encoder.PinRight);  // moved inside BindMobiFlightFreePins()
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFEncoderPanel.cs
> +            ////ComboBoxHelper.BindMobiFlightFreePins(mfLeftPinComboBox, Pins, encoder.PinLeft);
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFAnalogPanel.cs
> +            ////if (mfPinComboBox.Items.Count > 0)
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFAnalogPanel.cs
> +            //setValues();
simply remove.

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Device/MFLedSegmentPanel.cs
> +            bool ex_initialized = initialized;
no underscrore, camelCase is preferred

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Settings/MobiFlightPanel.cs
> +            TreeNode moduleNode = getModuleNode();
why are all these changes part of this PR?

2022-02-06 12:23 UTC, DocMoebiuz commented on UI/Panels/Settings/MobiFlightPanel.cs
> +            TreeNode moduleNode = getModuleNode();
it looks like because of the renaming.

2022-02-06 13:50 UTC, GioCC commented
Thanks for the indications; most of the requested changes were awaiting cleanup pending your review feedback (that's why the PR was in draft state). I will proceed to correct as per request.

2022-02-06 13:53 UTC, DocMoebiuz commented
@GioCC - cool, thanks!!!

2022-02-06 14:47 UTC, GioCC commented
> * It not easy to review the changes because sometimes, some lines were only moved around, and indenting got changed - (e.g. MFAnalogPanel.cs).

I think this is sometimes caused by different editor settings (eg tab lengths and the like); lines moving was probably in the attempt to make identical code more uniform in different places (or the flow more meaningful), although obviously I'd need to see where it occurred.

> * Please don't put comments at the end of the line. Always better on top, before the code.

I would normally disagree :) but of course guidelines are guidelines. Duly noted. 

> * Also for some reason it seems that the git history at least on my local main branch is not linear anymore. When you merge the main branch, do you merge rebase  or simply merge?

No, I usually simply merge by habit; I will definitely try and be more careful in the future.

> * Method normally are CamelCase.

Can't find anymore where I did differently, can you still recall some pointers so I can correct?

> * EventHandlers in C# have an "_eventname" when the Designer adds them, so that's why some methods contain an "_"

Ooooohhh... ok, I was scratching my head to try and remember what this was about, until I copied the text in the editor to reply... the underscore appeared, and suddenly everything made sense :D

2022-02-21 11:58 UTC, GioCC commented
Is there any other change required?

2022-02-24 09:09 UTC, GioCC commented
I reviewed the changes after your prompt, I believe almost everything is now in place, except possibly:
- there are still some (very short) comments on the end of the line; it did not look like a very big issue for this PR, so I left them, taking the notice for future modifications. If you think that's critical, I can go ahead and correct them.
- I did not try and correct spacing differences; that would probably require retracing the whole changes and reapply them one by one on the starting code base. Same considerations as above.
That's why I requested your review again, to confirm whether the points above can be accepted.

2022-02-26 12:38 UTC, DocMoebiuz requested changes
Ok, thanks so much for all your efforts.
Last tiny adjustment would be the naming for the 

update_lists() > UpdateFreePinsInDropDowns()
update_all() > RefreshFreePinsInDropDowns()

2022-02-26 12:38 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +            update_lists();
Let's change this to a more speaking name and use camel case:
 UpdateFreePinsInDropDowns()

2022-02-26 12:38 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +        private void update_lists()
Let's change this to a more speaking name and use camel case:
UpdateFreePinsInDropDowns()

2022-02-26 12:38 UTC, DocMoebiuz commented on UI/Panels/Device/MFShiftRegisterPanel.cs
> +        private void update_all(ComboBox comboBox)
Let's change this to a more speaking name and use camel case:
ReassignFreePinsInDropDowns()

2022-02-26 16:37 UTC, merged