Add extra debug info when run isn't turned on
MobiFlight/MobiFlight-Connector pull request #904
Opened 2022-09-11 13:04 UTC by neilenns

Fixes #903 

Add a little bit of extra info to the log message when a config is found. Here's what it looks like when run isn't turned on and you trigger an input:

`Debug	9/11/2022 6:02:33 AM	Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f. Run isn't enabled so the event wasn't sent to the simulator.`

Here's what it looks like when run is active (no change):

`Debug	9/11/2022 6:02:29 AM	Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f`

2022-09-11 19:56 UTC, DocMoebiuz requested changes
Thanks @neilenns !

Instead of mingling all into the one log statement, another simple place would be to simply adding it as a new line in 1606, before where the return is. 

Log....(Skipping execution of input action because MobiFlight is not started.)

Btw, "event wasn't sent to the simulator" is too specific because not all input actions deal with events to the sim, e.g. writing to a MF variable.

2022-09-11 20:14 UTC, neilenns commented
I wanted to include the text right on the log message for the event since that's what we typically see posted in Discord. 

Someone says "the simulator isn't responding when I press a button", then they enable logs, press a button, and say "see? MobiFlight got the keypress but nothing happened". By putting the extra text right on that log message it's really clear and easy to see.

I agree the current wording is kinda awkward. How about this variation:

```
Debug 9/11/2022 6:02:33 AM Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f. Skipping execution since run isn't enabled.
```

2022-09-11 20:16 UTC, neilenns commented
Do you mean something like this for two lines?

`

I wanted to include the text right on the log message for the event since that's what we typically see posted in Discord.

Someone says "the simulator isn't responding when I press a button", then they enable logs, press a button, and say "see? MobiFlight got the keypress but nothing happened". By putting the extra text right on that log message it's really clear and easy to see.

I agree the current wording is kinda awkward. How about this variation:

```
Debug 9/11/2022 6:02:33 AM Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f.
Debug 9/11/2022 6:02:33 AM Skipping execution since run isn't enabled.
```

2022-09-11 20:18 UTC, neilenns commented
Looks like this as two lines:

```
Debug	9/11/2022 1:17:51 PM	Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f. Run isn't enabled so the event wasn't sent to the simulator.
Debug	9/11/2022 1:17:51 PM	Skipping execution since run isn't enabled.
Debug	9/11/2022 1:17:52 PM	Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f. Run isn't enabled so the event wasn't sent to the simulator.
Debug	9/11/2022 1:17:52 PM	Skipping execution since run isn't enabled.
Debug	9/11/2022 1:17:53 PM	Config found for Encoder: ENC1 (RIGHT)@SN-eaf-59f. Run isn't enabled so the event wasn't sent to the simulator.
Debug	9/11/2022 1:17:53 PM	Skipping execution since run isn't enabled.
```

2022-09-29 10:58 UTC, DocMoebiuz requested changes
I still propose to log it as part of the if-branch in 1606. Super clear to read.
debug log message and then the return.

2022-09-29 13:37 UTC, neilenns commented
I'll move it to the if statement later today

2022-09-29 13:57 UTC, DocMoebiuz commented
> I'll move it to the if statement later today

super cool!

2022-09-29 16:50 UTC, neilenns commented
@DocMoebiuz Updated!

2022-09-29 20:58 UTC, DocMoebiuz approved these changes
Thanks!

2022-09-29 20:58 UTC, merged